### ISSUE TITLE
Cannot find the pretrained model in any of these GitHub folders

### ISSUE THREAD

**Issue by olgasparyan** [Erechtheus/geolocation#13]
Hi, I am trying to use your pertained models to apply the geolocation identification for some of my twitter data, however, I cannot find the pretrained models anywhere. 
Thanks in advance.

**Comment by Erechtheus** [comment]
The models are too large for GitHub repositories. The models are located here: https://drive.google.com/open?id=12L8BNQ9zTi6MehoQEILGKFy4pw0mVZGa

**Comment by Erechtheus** [comment]
Ticked closed. Please re-open if the problem persists
